// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT9jJou4iz5NZdwK8gDr4U_WLwUbA9kt4',
    appId: '1:645056492006:web:f4cfeb89d6b35219e5e627',
    messagingSenderId: '645056492006',
    projectId: 'my-notesvandanpr',
    authDomain: 'my-notesvandanpr.firebaseapp.com',
    storageBucket: 'my-notesvandanpr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQMbS8jV_pISXOP3s7620ghXvR-mUe5E',
    appId: '1:645056492006:android:455af66a27caa919e5e627',
    messagingSenderId: '645056492006',
    projectId: 'my-notesvandanpr',
    storageBucket: 'my-notesvandanpr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7_osjfj2qGkwKZG3gxjrfK7cOnw9k0Rg',
    appId: '1:645056492006:ios:5817fbf91be57c28e5e627',
    messagingSenderId: '645056492006',
    projectId: 'my-notesvandanpr',
    storageBucket: 'my-notesvandanpr.appspot.com',
    iosClientId: '645056492006-4se1ak54o9keioc03knj9diel6nej0sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVandan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7_osjfj2qGkwKZG3gxjrfK7cOnw9k0Rg',
    appId: '1:645056492006:ios:0ebb038e2a3cc638e5e627',
    messagingSenderId: '645056492006',
    projectId: 'my-notesvandanpr',
    storageBucket: 'my-notesvandanpr.appspot.com',
    iosClientId: '645056492006-snk7kna5h28ihqg1prjokoqp3kteb6ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVandan.RunnerTests',
  );
}
